### ISSUE TITLE
Sidebar slide and Summernote issue

### ISSUE THREAD

**Issue by dream811** [InfyOmLabs/laravel-ui-adminlte#7]
I am using your fantastic laravel-ui-adminlte on laravel 8.
I need your help.
![image](https://user-images.githubusercontent.com/45660446/102380114-81febe00-4002-11eb-9aaf-ca703747100b.png)
![image](https://user-images.githubusercontent.com/45660446/102380335-c38f6900-4002-11eb-82e5-c19882471b09.png)
thanks

**Comment by ShaileshInfyom** [comment]
this is does not produce any more 
![image](https://user-images.githubusercontent.com/28335166/150919996-fb9aff7f-22f6-4e0c-b83f-599494e54033.png)
