### ISSUE TITLE
Error while installing or updateting packages

### ISSUE THREAD

**Issue by designoble** [InfyOmLabs/laravel-ui-adminlte#8]
Hi, 
I am getting this error while installing any new packages or updating composer.
Seems this is causing by laravel-ui-adminlte
Please help. Thanks :) 

![image_2021_04_22T06_23_13_841Z](https://user-images.githubusercontent.com/79092947/115666925-01ace880-a367-11eb-95e5-cb05d475f127.png)

**Comment by hichxm** [comment]
Me too, just need to alter your PHP version to 7.3 or 7.4

**Comment by mitulgolakiya** [comment]
I will consider adding PHP 8 support this week.

**Comment by ihtishamKhan** [comment]
Not working for me also, no support of PHP 8

**Comment by mitulgolakiya** [comment]
@ihtishamKhan which version you are using? and what error you are getting? since 3.2.0 is already supported by PHP 8.0

**Comment by vishalinfyom** [comment]
> Hi, I am getting this error while installing any new packages or updating composer. Seems this is causing by laravel-ui-adminlte Please help. Thanks :)
> 
> ![image_2021_04_22T06_23_13_841Z](https://user-images.githubusercontent.com/79092947/115666925-01ace880-a367-11eb-95e5-cb05d475f127.png)

Please use the latest version `v3.2.0` its already supports PHP 8.0

Thanks
