### ISSUE TITLE
Fails at npm run dev

### ISSUE THREAD

**Issue by nguyenhychan** [InfyOmLabs/laravel-ui-adminlte#9]
I have tried to install this package to my fresh new Laravel 8 project following the guidelines here:

https://levelup.gitconnected.com/integrating-adminlte-3-and-laravel-8-51c1555efa60

And I have found that on the second try running npm run dev, I got the following error:

```
ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
5 │ @import '~admin-lte/build/scss/AdminLTE';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  /home/webadmin/projects/test-dump/test-app/resources/sass/app.scss 5:9  root stylesheet
    at processResult (/home/webadmin/projects/test-dump/test-app/node_modules/webpack/lib/NormalModule.js:701:19)
    at /home/webadmin/projects/test-dump/test-app/node_modules/webpack/lib/NormalModule.js:807:5
    at /home/webadmin/projects/test-dump/test-app/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /home/webadmin/projects/test-dump/test-app/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/home/webadmin/projects/test-dump/test-app/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /home/webadmin/projects/test-dump/test-app/node_modules/sass-loader/dist/index.js:73:7
    at Function.call$2 (/home/webadmin/projects/test-dump/test-app/node_modules/sass/sass.dart.js:93417:16)
    at _render_closure1.call$2 (/home/webadmin/projects/test-dump/test-app/node_modules/sass/sass.dart.js:81775:12)
    at _RootZone.runBinary$3$3 (/home/webadmin/projects/test-dump/test-app/node_modules/sass/sass.dart.js:27547:18)
    at _FutureListener.handleError$1 (/home/webadmin/projects/test-dump/test-app/node_modules/sass/sass.dart.js:26096:19)
```

I found that this was different from the tutorial and also makes the project fail. Did any update screw things up probably?

Also it has come to my attention that it seems that this package is no longer maintained in a properly manner. I just wonder if there are any developers still caring for this package and trying to resolve the issues raised by others (as far as I know there are two open issues with none resolved to any extent). This is not good.

**Comment by M1hai** [comment]
@nguyenhychan I fixed this by going to resources/sass/app.scss and replace line 5 like this:

`@import '~admin-lte/build/scss/adminlte';`

Then it seems to be working ok

**Comment by jilcimar** [comment]
> @nguyenhychan I fixed this by going to resources/sass/app.scss and replace line 5 like this:
> 
> `@import '~admin-lte/build/scss/adminlte';`
> 
> Then it seems to be working ok

Thanks, solved my problem too!
